spring.application.name=facturacion

# Credenciales locales (cada integrante tiene su propio db-local.properties, ignorado por git)
spring.config.import=optional:classpath:db-local.properties

# CONEXIÓN POSTGRESQL (Tomado de tu persistence.xml)
spring.datasource.url=jdbc:postgresql://localhost:5432/TP_GRUPAL_ORM
spring.datasource.username=postgres
spring.datasource.password=pw
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
